# popclip
name: Run in Terminal
identifier: com.apple.terminal.popclip.run
icon: iconify:mdi:console
description: Open selected text as a command in a new macOS Terminal window.
app:
  name: Terminal
  bundle identifiers: [com.apple.Terminal]
actions:
  - title: Run in Terminal
    icon: iconify:mdi:console
    shell script file: run.sh
    